### ISSUE TITLE
AttributeError: 'SolidLocaleRegexURLResolver' object has no attribute 'prefix_default_language'

### ISSUE THREAD

**Issue by jorenham** [st4lk/django-solid-i18n-urls#40]
After upgrading from Django 1.9.13 to 1.10.5, my project won't run anymore with the traceback:

```
Internal Server Error: /
Traceback (most recent call last):
  File "/home/joren/workspace/myproject/lib/python3.4/site-packages/django/core/handlers/base.py", line 131, in get_response
    response = middleware_method(request, response)
  File "/home/joren/workspace/myproject/lib/python3.4/site-packages/django/middleware/locale.py", line 36, in process_response
    i18n_patterns_used, prefixed_default_language = is_language_prefix_patterns_used(urlconf)
  File "/home/joren/workspace/myproject/lib/python3.4/functools.py", line 448, in wrapper
    result = user_function(*args, **kwds)
  File "/home/joren/workspace/myproject/lib/python3.4/site-packages/django/conf/urls/i18n.py", line 31, in is_language_prefix_patterns_used
    return True, url_pattern.prefix_default_language
AttributeError: 'SolidLocaleRegexURLResolver' object has no attribute 'prefix_default_language'
[31/Jan/2017 13:03:57] "GET / HTTP/1.1" 500 82666
```

I'm using the setting `SOLID_I18N_USE_REDIRECTS = True` and it all seem to work fine at Django 1.9.13. What's going on here?

**Comment by st4lk** [comment]
Hi Jorem, thanks for catching that!
Looks like a bug.
Django's [`LocaleRegexURLResolver`](https://github.com/django/django/blob/stable/1.10.x/django/urls/resolvers.py#L405) have a new argument `prefix_default_language`, which is saved as property:
```
    def __init__(
        self, urlconf_name, default_kwargs=None, app_name=None, namespace=None,
        prefix_default_language=True,
    ):
        super(LocaleRegexURLResolver, self).__init__(
            None, urlconf_name, default_kwargs, app_name, namespace,
        )
        self.prefix_default_language = prefix_default_language
```

But [`SolidLocaleRegexURLResolver`](https://github.com/st4lk/django-solid-i18n-urls/blob/master/solid_i18n/urlresolvers.py#L16) doesn't pass this argument in `__init__`:
```
    def __init__(self, urlconf_name, default_kwargs=None, app_name=None, namespace=None):
        super(LocaleRegexURLResolver, self).__init__(
            None, urlconf_name, default_kwargs, app_name, namespace)
        self.compiled_with_default = False
```
We need a fix here.

**Comment by st4lk** [comment]
Fixed possibly related issue and uploaded new version [v1.4.1](https://pypi.python.org/pypi/solid_i18n/1.4.1).
But very likely you faced this exception because you have 
```
'django.middleware.locale.LocaleMiddleware'
```
In the list of your `MIDDLEWARE_CLASSES`. If you want to use this package, you must remove it.
Also, check [deprecation notice](https://github.com/st4lk/django-solid-i18n-urls#deprecation-notice).
